<?php

return [
    'categories' => 'Manage Categories',
    'products' => 'Manage Products',
    'brands' => "Manage Brands",
    'coupons' => 'Manage Coupons',
    'orders' => 'Manage Orders',
    'users' => 'Manage Users',
    'roles' => 'Manage Roles',
    'settings' => 'Manage Settings',
    'reports' => 'Manage Reports',
    'dashboard' => 'Manage Dashboard',
    'profile' => 'Manage Profile',
    'home' => 'Manage Home',
    'contact' => 'Manage Contact',
    'about' => 'Manage About',
    'blog' => 'Manage Blog',
    'newsletters' => 'Manage Newsletters',
    'banners' => 'Manage Banners',
    'pages' => 'Manage Pages',
    'sliders' => 'Manage Sliders',
    'faqs' => 'Manage FAQs',
    'socials' => 'Manage Socials',
    'menus' => 'Manage Menus',
    'comments' => 'Manage Comments',
    'admins' => 'Manage Admins',
];
